export const KNEXREAD_TAB_BAR_HEIGHT = 40;
export const KNEXREAD_TAB_BUTTON_HEIGHT = 38;
export const KNEXREAD_RIBBON_HEIGHT = 48;
export const KNEXREAD_GUIDES_BAR_HEIGHT = 36;
export const KNEXREAD_BACKSTAGE_SPACER_HEIGHT =
  KNEXREAD_RIBBON_HEIGHT + KNEXREAD_GUIDES_BAR_HEIGHT;
