/**
 * Responsabilidade do arquivo:
 * - Centralizar catalogo operacional de familias do pipeline.
 * - Padronizar IDs de auditoria sem mover logica de execucao para o registry.
 * - Permitir consulta por ID e por camada para observabilidade/governanca.
 */
import type { FamilyDefinition } from "./family-types";

export const FAMILY_REGISTRY: FamilyDefinition[] = [
  {
    id: "greeting_minimum",
    label: "Greeting / Conversational Minimum",
    layer: "pre-route",
    cost: "minimal",
    activationMode: "always-light",
    description: "Detecta saudacoes, fala fatica e interacao minima.",
    preferredRoute: ["minimum"],
    tags: ["chat", "greeting", "lightweight"],
  },
  {
    id: "verifiable_fact",
    label: "Verifiable Fact Family",
    layer: "pre-route",
    cost: "low",
    activationMode: "intent-gated",
    description: "Detecta necessidade de verificacao factual e factualidade sensivel ao tempo.",
    preferredRoute: ["inferential", "quantum-state"],
    preferredSteps: ["fact_check", "retrieval", "evidence_alignment", "web_search"],
    tags: ["fact", "verification", "source", "recency"],
  },
  {
    id: "recency_signal",
    label: "Recency Signal Family",
    layer: "pre-route",
    cost: "minimal",
    activationMode: "always-light",
    description: "Detecta pedidos com dependencia temporal ou recencia.",
    preferredRoute: ["inferential", "quantum-state"],
    preferredSteps: ["web_search"],
    tags: ["time", "latest", "recent"],
  },
  {
    id: "quick_safety",
    label: "Quick Safety Family",
    layer: "pre-route",
    cost: "minimal",
    activationMode: "always-light",
    description: "Detecta rapidamente risco de safety antes de camadas profundas.",
    preferredRoute: ["minimum"],
    tags: ["safety", "block", "risk"],
  },
  {
    id: "input_intent",
    label: "Input Intent Family",
    layer: "input",
    cost: "low",
    activationMode: "always-light",
    description: "Classifica intencao principal do pedido.",
    tags: ["intent", "classification"],
  },
  {
    id: "input_domain",
    label: "Input Domain Family",
    layer: "input",
    cost: "low",
    activationMode: "domain-gated",
    description: "Classifica o dominio do pedido.",
    tags: ["domain", "classification"],
  },
  {
    id: "input_urgency",
    label: "Input Urgency Family",
    layer: "input",
    cost: "minimal",
    activationMode: "always-light",
    description: "Classifica urgencia e prioridade operacional.",
    tags: ["urgency", "priority"],
  },
  {
    id: "pragmatic_signals",
    label: "Pragmatic Signals Family",
    layer: "language",
    cost: "medium",
    activationMode: "route-gated",
    description: "Consolida ato de fala, forca diretiva, polidez e pedido indireto.",
    preferredRoute: ["reflective", "inferential", "quantum-state"],
    tags: ["pragmatics", "speech-act"],
  },
  {
    id: "surface_semantics",
    label: "Surface Semantics Family",
    layer: "language",
    cost: "medium",
    activationMode: "route-gated",
    description: "Consolida ancoras semanticas, entidades, ambiguidade e escopo.",
    preferredRoute: ["reflective", "inferential", "quantum-state"],
    tags: ["semantics", "ambiguity", "entities"],
  },
  {
    id: "discourse_form",
    label: "Discourse Form Family",
    layer: "language",
    cost: "medium",
    activationMode: "route-gated",
    description: "Analisa repeticao, progressao e fragmentacao discursiva.",
    preferredRoute: ["reflective", "inferential", "quantum-state"],
    tags: ["discourse", "structure"],
  },
  {
    id: "mode_selection",
    label: "Mode Selection Family",
    layer: "orchestration",
    cost: "low",
    activationMode: "always-light",
    description: "Seleciona modo operacional da resposta.",
    tags: ["mode", "planning"],
  },
  {
    id: "step_planning",
    label: "Step Planning Family",
    layer: "orchestration",
    cost: "medium",
    activationMode: "route-gated",
    description: "Planeja steps reais do pipeline.",
    tags: ["steps", "plan", "execution"],
  },
  {
    id: "knowledge_retrieval",
    label: "Knowledge Retrieval Family",
    layer: "knowledge",
    cost: "high",
    activationMode: "step-gated",
    description: "Executa retrieval local, alinhamento e consolidacao de evidencia.",
    preferredRoute: ["inferential", "quantum-state"],
    preferredSteps: ["retrieval", "retrieval_augmented", "research", "fact_check"],
    tags: ["knowledge", "retrieval", "evidence"],
  },
  {
    id: "web_fact_verification",
    label: "Web Fact Verification Family",
    layer: "knowledge",
    cost: "very-high",
    activationMode: "step-gated",
    description: "Executa pesquisa externa para fatos volateis.",
    preferredRoute: ["quantum-state"],
    preferredSteps: ["web_search", "fact_check"],
    tags: ["web", "verification", "recency"],
  },
  {
    id: "critical_reflection",
    label: "Critical Reflection Family",
    layer: "reflective",
    cost: "high",
    activationMode: "step-gated",
    description: "Extrai assumptions, caveats e tensoes.",
    preferredRoute: ["reflective", "inferential", "quantum-state"],
    preferredSteps: ["reflection", "critical_reflection", "assumption_scan"],
    tags: ["reflection", "caveat", "uncertainty"],
  },
  {
    id: "inferential_projection",
    label: "Inferential Projection Family",
    layer: "inferential",
    cost: "high",
    activationMode: "step-gated",
    description: "Gera implicacoes, cenarios e efeitos de segunda ordem.",
    preferredRoute: ["inferential", "quantum-state"],
    preferredSteps: ["inference", "scenario_projection", "second_order_reasoning"],
    tags: ["inference", "projection", "scenario"],
  },
  {
    id: "academic_normalization",
    label: "Academic Normalization Family",
    layer: "academic",
    cost: "medium",
    activationMode: "intent-gated",
    description: "Aplica normalizacao academica quando o modo exigir formalidade.",
    preferredRoute: ["reflective", "inferential", "quantum-state"],
    tags: ["academic", "formal", "normalization"],
  },
  {
    id: "validation_factual",
    label: "Validation Factual Family",
    layer: "validation",
    cost: "high",
    activationMode: "validation-gated",
    description: "Valida factualidade, alinhamento com fontes e risco de alucinacao.",
    tags: ["validation", "factual", "quality"],
  },
  {
    id: "validation_policy",
    label: "Validation Policy Family",
    layer: "validation",
    cost: "medium",
    activationMode: "validation-gated",
    description: "Valida politica, privacy e safety de saida.",
    tags: ["validation", "policy", "safety"],
  },
  {
    id: "observability_metrics",
    label: "Observability Metrics Family",
    layer: "observability",
    cost: "low",
    activationMode: "always-light",
    description: "Agrega metricas por rota, camada e motivo de skip.",
    tags: ["metrics", "observability"],
  },
];

export function getFamilyById(id: string) {
  return FAMILY_REGISTRY.find((item) => item.id === id);
}

export function getFamiliesByLayer(layer: FamilyDefinition["layer"]) {
  return FAMILY_REGISTRY.filter((item) => item.layer === layer);
}

