    location /auth/ {
        proxy_pass http://auth:4000/;
    }
    location /portal/ {
        proxy_pass http://portal:3000/;
    }
    location /vioclass/ {
        proxy_pass http://vioclass:3200/;
    }
    location /violive/ {
        proxy_pass http://violive:3400/;
    }
    location /supadrive/ {
        proxy_pass http://supadrive:3300/;
    }
    location /viohub/ {
        proxy_pass http://viohub:3500/;
    }
