server {
    listen 443 ssl;
    server_name workspace.localhost;

    location /auth/ {
        proxy_pass http://auth:4000/;
    }

    location /portal/ {
        proxy_pass http://portal:3000/;
    }

    location /upgrade/ {
        proxy_pass http://upgrade:3200/;
    }

    location /supadrive/ {
        proxy_pass http://supadrive:3300/;
    }

    location /viohub/ {
        proxy_pass http://viohub:3400/;
    }
}
