import {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Bold,
  ClipboardCopy,
  ClipboardPaste,
  FilePlus2,
  FileUp,
  FolderOpen,
  Image,
  Italic,
  Link,
  List,
  ListOrdered,
  Save,
  Search,
  Table,
  Underline,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";

export const ribbonIcons = {
  bold: Bold,
  italic: Italic,
  underline: Underline,
  copy: ClipboardCopy,
  paste: ClipboardPaste,
  save: Save,
  newFile: FilePlus2,
  openFile: FolderOpen,
  importFile: FileUp,
  image: Image,
  table: Table,
  link: Link,
  bulletList: List,
  orderedList: ListOrdered,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,
  alignRight: AlignRight,
  alignJustify: AlignJustify,
  search: Search,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
} satisfies Record<string, LucideIcon>;

