export type PipelineRoute = "minimum" | "reflective" | "inferential" | "quantum-state";

export type PipelineLayerId =
  | "pipeline"
  | "input"
  | "language"
  | "conversation"
  | "affective-signal"
  | "response-behavior"
  | "context"
  | "orchestration"
  | "memory"
  | "response-planning"
  | "knowledge"
  | "quantum"
  | "preparatory"
  | "reflective"
  | "inferential"
  | "metacognitive"
  | "founder-influence"
  | "epistemic-integration"
  | "generation"
  | "structure"
  | "academic-normalization"
  | "validation"
  | "proactivity-gate"
  | "delivery-profile"
  | "linguistic-humanizer"
  | "response-calibration"
  | "validation-final"
  | "presentation"
  | "observability"
  | "feedback";
